### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by likeanowl** [ml-in-programming/topias#3]
- [x] Change history parsing scheme, because methods could be moved or renamed and changes must be matched by full method name, not by reference
- [x] Change state scheme (remove PsiElement pointer, because it seems to be not needed)
- [x] Integrate with RefactoringMiner

**Comment by likeanowl** [comment]
new bunch of issues has arrived:
- [ ] fix issue with methods borders
- [ ] handle editor new lines adding (auto incrementing startOffset in MethodInfo instance)

**Comment by likeanowl** [comment]
- [ ] label deletion when line below is deleted --- must handle somehow
- [ ] label deletion when method below is deleted
- [ ] label change when adding line "from below
- [ ] test all refactoring cases
- [ ] make working on big repos
- [ ] delete method from collection if it was deleted in Change.Modified case
- [ ] somehow save date of change for further data visualization

**Comment by likeanowl** [comment]
- [ ] settings UI
- [ ] fix statistics calculation
- [ ] fix issues with gradle
- [ ] do something for bd patches saving

**Comment by likeanowl** [comment]
- [ ] implement psi navigation: https://github.com/CodeMangler/JumpToUsage
- [ ] add issues lib
- [ ] DEBUG DEBUG DEBUG!!!1111!
